"""Crear tabla Imagen

Revision ID: deadc0391621
Revises: d0c7b8e4b57c
Create Date: 2025-05-07 21:58:10.689744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deadc0391621'
down_revision = 'd0c7b8e4b57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=500), nullable=True),
    sa.Column('nombre_archivo', sa.String(length=500), nullable=True),
    sa.Column('n_pixeles_total', sa.Integer(), nullable=True),
    sa.Column('tipo_transformacion', sa.String(length=50), nullable=True),
    sa.Column('n_pixeles_azules', sa.Integer(), nullable=True),
    sa.Column('n_pixeles_verdes', sa.Integer(), nullable=True),
    sa.Column('n_pixeles_rojos', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagen')
    # ### end Alembic commands ###
